// <auto-generated />
using System;
using EntityFramework_lesson;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework_lesson.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250812161826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EntityFramework_lesson.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("apps");
                });

            modelBuilder.Entity("EntityFramework_lesson.Guarantee", b =>
                {
                    b.Property<int>("PhoneId")
                        .HasColumnType("int")
                        .HasColumnName("phone_id");

                    b.Property<int>("Months")
                        .HasColumnType("int")
                        .HasColumnName("months");

                    b.HasKey("PhoneId");

                    b.ToTable("Guarantees");
                });

            modelBuilder.Entity("EntityFramework_lesson.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("phones");
                });

            modelBuilder.Entity("EntityFramework_lesson.SoftwareUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PhoneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("release_date");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PhoneId");

                    b.ToTable("software_updates");
                });

            modelBuilder.Entity("EntityFramework_lesson.Guarantee", b =>
                {
                    b.HasOne("EntityFramework_lesson.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("EntityFramework_lesson.Phone", b =>
                {
                    b.HasOne("EntityFramework_lesson.App", null)
                        .WithMany("Phones")
                        .HasForeignKey("AppId");
                });

            modelBuilder.Entity("EntityFramework_lesson.SoftwareUpdate", b =>
                {
                    b.HasOne("EntityFramework_lesson.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("EntityFramework_lesson.App", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
